language: go
go:
  - 1.7
install:
# Install external dependencies
  - go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq)
  - ./build static
  - sudo ./install
script:
  - ./test
