version: '2'

services:
  elasticsearch:
    image: elasticsearch
    ports:
     - 9200:9200

  kibana:
    image: kibana
    ports:
     - 5601:5601

#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#     - 15672:15672
#     - 5672:5672
#
#  db:
#    image: pgfbpipeline
#    ports:
#     - 5432:5432
